FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    clang \
    && rm -rf /var/lib/apt/lists/*

COPY hello.c /app/hello.c

WORKDIR /app

RUN clang hello.c -o hello_clang

CMD ["./hello_clang"]