# ================== Database Settings ==================
db_host=localhost
db_port=5432
db_name=put_your_own_db_name_here
db_user=postgres
db_password=put_your_own_password_here

# ================== Indexer Settings ==================
start_directory=.
file_extensions=bat,md,txt