# ================== Database Settings ==================
db_host=localhost
db_port=5432
db_name=search_engine
db_user=postgres
db_password=12345

# ================== Indexer Settings ==================
start_directory=..
file_extensions=bat